{
  "sender_id": "750e335a-e057-4b98-a54a-2093207f1eb2:51953376-fb7e-4785-9b4c-6f8b8d6b43f4:6948da9d-1a10-41c4-a1b8-339fd6a55c98",
  "send_metrics": true,
  "send_errors": true,
  "disable_logging": false
}